[auth]
redirect_uri="https://1test-gogle9.streamlit.app/"
cookie_secret="dfwfOCSPX-sfmwfoHYkNZLAnu2h-OYukefef"

[auth.google]
client_id="122731957441-biqm8h2rc0kusl35jo49entk68tcuqcs.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"
